### ISSUE TITLE
REDCap 12.0.23LTS

### ISSUE THREAD

**Issue by ajperdew** [lsgs/redcap-event-navigation-tweaks#1]
I'm having trouble getting this module to work after upgrading to REDCap 12.0.23LTS. Specifically, the Data Entry Form event display is not appearing. The other two features seem to work as expected.  Any advice?

Thanks!

**Comment by lsgs** [comment]
Sorry it's been a while @ajperdew. I have not been experiencing any problems in standard release 12.2.11 or (now) 12.5.16. Are you still having trouble?
