### ISSUE TITLE
Array TypeError at line 340

### ISSUE THREAD

**Issue by dormistonsmith** [lsgs/redcap-event-navigation-tweaks#8]
```
The 'event_navigation_tweaks' module threw the following exception when calling the hook method 'redcap_data_entry_form_top':

TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in .../redcap/modules/event_navigation_tweaks_v1.1.1/EventNavigationTweaks.php:340
```

Looks very similar to the error (array_keys vs array_key_exists) from issue #7 so hopefully whatever the fix was for that should work if deployed here too?

**Comment by lsgs** [comment]
Thanks for reporting this @dormistonsmith. We've been getting some too but I have done a fix and submitted it to VUMC, so look out for v1.1.2 appearing soon.
